### ISSUE TITLE
[APP-0106] Add validate jwt token by ci_session, create refresh token and add response for /api/common/user_info

### ISSUE THREAD

**Issue by CheIby** [Project-IPCA/ipca-backend#155]
### Descripion
**ENDPOINT** `GET` /api/common/user_info

**RESPONSE** 
```json
{
 "user_info": {
   "user_id": "string",
   "avatar": "string",
   "f_name": "string", 
   "l_name": "string",
   "nickname": "string",
   "gender": "string",
   "dob": "datetime",
   "dept": {
     "id": 1,
     "name": "string"
   },
   "email": "string",
   "tel": "string",
   +++ "kmitl_id": "string",
   +++ "group_info": {
     "group_id": "string(uuid)",
     "name": "string",
     "number": 1,
     "day": "string",
     "time_start": "string",
     "time_end": "string", 
     "year": 1,
     "semester": 1,
     "instructor": "string"
   }
 },
 "selected": {
   "departments": [
     {
       "id": 1,
       "name": "string"
     }
   ]
 }
}
```

**ENDPOINT** `POST` /api/auth/refresh_token

**RESPONSE** 
```
{
 "accessToken": "string",
 "refreshToken": "string",
 "exp": 1
}
```

### Task
- [x] Add logic to handle old jwt token but not expire
- [x] Add kmitl_id and group_info to response
- [x] Create `GET` /api/auth/refresh_token
